#!/usr/bin/env python3
"""Generate sound.inc -- the two filter-cutoff sweep tables (SPEC.md Section 8).

The "boing" is a resonant low-pass cutoff collapsing over a noise burst.  The
collapse is a linear ramp in $D416 (cutoff high byte) read one entry per frame:
floor 220 -> 30, wall 250 -> 70, both over the 16 frames the sweep lasts.

The tables are 24 entries even though the ramp is 16, because snd_timer runs
0-23 and sound_step indexes with it.  Entries 16-23 hold the final value, so a
table read outside the sweep window is still a defined byte rather than
whatever followed the table in RODATA.  SPEC.md Section 8 calls these "a linear
ramp" of 24 entries, which taken literally would spread the ramp over all 24 and
contradict its own schedule table ("at 0-15, write $D416 from the sweep table");
the 16-then-hold reading is the one that satisfies both, and it is what the
schedule in Section 8 and PLAN.md Task 5 both describe.

Stdlib only, no arguments; writes ../sound.inc relative to this file.
"""

from pathlib import Path

# SPEC.md Section 8: the wall stays brighter throughout -- a wall is a harder,
# smaller surface than the floor.
SWEEPS = (
    ("cut_floor", 220, 30),
    ("cut_wall", 250, 70),
)

RAMP = 16               # frames the cutoff sweeps over (snd_timer 0-15)
ENTRIES = 24            # table length: snd_timer's whole 0-23 range


def ramp(start: int, end: int) -> list[int]:
    """RAMP entries falling start -> end, then ENTRIES-RAMP entries holding end.

    Rounded with floor(x + 0.5) rather than round(), because round() is
    banker's rounding: it would pull some .5 steps up to the previous entry's
    value and break the "monotonically non-increasing" assert below on a table
    whose true slope is monotone.
    """
    span = RAMP - 1
    vals = [int((start + (end - start) * i / span) + 0.5) for i in range(RAMP)]
    return vals + [end] * (ENTRIES - RAMP)


def main() -> None:
    lines = [
        "; sound.inc -- GENERATED by tools/gen_sound.py.  Do not edit: change",
        "; the generator and re-run it.",
        ";",
        "; Two filter-cutoff sweeps for $D416, one entry per frame, indexed by",
        f"; snd_timer.  Each falls over {RAMP} frames and then holds, so an index",
        f"; anywhere in snd_timer's 0-{ENTRIES - 1} range reads a defined byte.",
        "; The descending resonant low-pass over a noise burst is the whole",
        '; "boing" -- a struck elastic surface whose brightness collapses as the',
        "; strike energy leaves it (SPEC.md Section 8).",
        "",
        '        .segment "RODATA"',
    ]

    tables: dict[str, list[int]] = {}
    for name, start, end in SWEEPS:
        vals = ramp(start, end)
        tables[name] = vals
        lines += [
            "",
            f"; {name} -- {start} -> {end} over frames 0-{RAMP - 1}, "
            f"then {end} to frame {ENTRIES - 1}.",
            f"{name}:",
        ]
        for i, v in enumerate(vals):
            held = "  (hold)" if i >= RAMP else ""
            lines.append(f"        .byte {v:3d}                    "
                         f"; frame {i:2d}{held}")
    lines.append("")

    # --- asserts: fail loudly rather than emit something short -------------
    for (name, start, end), vals in zip(SWEEPS, tables.values()):
        assert len(vals) == ENTRIES, \
            f"{name}: emitted {len(vals)} entries, expected {ENTRIES}"
        assert vals[0] == start, f"{name}: starts at {vals[0]}, spec says {start}"
        assert vals[-1] == end, f"{name}: ends at {vals[-1]}, spec says {end}"
        assert vals[RAMP - 1] == end, \
            f"{name}: frame {RAMP - 1} is {vals[RAMP - 1]}, spec says {end}"
        assert all(0 <= v <= 255 for v in vals), f"{name}: a value is not a byte"
        assert all(b <= a for a, b in zip(vals, vals[1:])), \
            f"{name}: not monotonically non-increasing: {vals}"
    # The wall is brighter than the floor at every frame -- the reason there are
    # two tables at all.
    assert all(w > f for w, f in zip(tables["cut_wall"], tables["cut_floor"])), \
        "cut_wall is not brighter than cut_floor at every frame"

    out = Path(__file__).resolve().parent.parent / "sound.inc"
    out.write_text("\n".join(lines))

    print(f"{out}: {len(SWEEPS)} tables x {ENTRIES} bytes")
    for name, vals in tables.items():
        print(f"  {name}: {vals}")


if __name__ == "__main__":
    main()
