#!/usr/bin/env python3
"""Generate bounce.inc -- the ball's vertical motion, one 8.8 entry per phase.

SPEC.md Section 6.1: the bounce is PARABOLIC, not sinusoidal, because a
parabola's second derivative is a constant and that constant is what free fall
is.  Sprite-0 Y at phase p of P = 64 frames:

    y(p) = Y_FLOOR - A * 4 * p * (P - p) / P^2
         = 158 - 104 * p * (64 - p) / 1024

Evaluated here, once, and shipped as a table: at 60 Hz the alternative is a
multiply and a divide inside the raster interrupt, for a curve that is the same
64 numbers every bounce.

The table is 8.8 fixed point, low byte (fraction) first, because that is the
order the 6502 wants -- `lda bounce_tab,x` / `lda bounce_tab+1,x` with
x = 2 * bounce_phase lands the fraction in ball_yf and the integer in ball_yi
with no reordering.

Every entry is EXACT in 8.8, with no rounding at all:

    y(p) * 256 = 158 * 256 - 104 * p * (64 - p) * 256 / 1024
               = 40448 - 26 * p * (64 - p)

so the generator does integer arithmetic and the assert that the table is
symmetric about p = 32 is an equality, not a tolerance.

A DRAFT of SPEC.md Section 6.1 tabulated y(16) = y(48) = 79.0 and
y(24) = y(40) = 57.5 where the formula gives 80.0 and 60.5, and that table was
not even self-consistent -- 79.0 at p = 16 implies an amplitude of 105.3 and
57.5 at p = 24 implies 107.2, so no single A reproduces both.  The formula won,
because it is what the values the spec asserts elsewhere (y(0) = 158 at contact,
y(32) = 54 at the apex, and the 104-raster amplitude between them) agree with.
Section 6.1 now prints 80.0 and 60.5 and records the correction in its own
parenthesis; this note stays because the numbers below are the only place the
claim can be checked.

Stdlib only, no arguments; writes ../bounce.inc relative to this file.
"""

from pathlib import Path

# --- SPEC.md Section 6.1 ---------------------------------------------------
P = 64                  # frames per bounce -- 1.067 s at 60 Hz
Y_FLOOR = 158           # sprite-0 Y at contact: the sphere spans rasters 164-235
AMP = 104               # apex is 104 rasters above contact, so y(32) = 54

# y(p) * 256 = Y_FLOOR * 256 - (AMP * 4 * 256 / P^2) * p * (P - p), and
# 104 * 4 * 256 / 4096 = 26 exactly, which is why no entry needs rounding.
SCALE = AMP * 4 * 256 // (P * P)
assert SCALE * P * P == AMP * 4 * 256, \
    f"amplitude {AMP} is not exact in 8.8 over {P} frames"

# The sprite Y window (skills/6502-assembly/SKILL.md, "Sprite invisible?").  An
# entry outside it is a ball that vanishes for part of its arc.
Y_MIN, Y_MAX = 50, 249


def y88(p: int) -> int:
    """y(p) in 8.8 fixed point, exactly."""
    return Y_FLOOR * 256 - SCALE * p * (P - p)


def main() -> None:
    table = [y88(p) for p in range(P)]

    lines = [
        "; bounce.inc -- GENERATED by tools/gen_bounce.py.  Do not edit: change",
        "; the generator and re-run it.",
        ";",
        f"; {P} entries x 2 bytes = {P * 2} bytes of 8.8 fixed point, FRACTION",
        "; byte first, so that with x = 2 * bounce_phase the pair",
        "; `lda bounce_tab,x` / `lda bounce_tab+1,x` fills ball_yf then ball_yi.",
        ";",
        f"; y(p) = {Y_FLOOR} - {AMP} * 4 * p * ({P} - p) / {P}^2, a parabola:"
        "  d2y/dp2 is a",
        "; constant, which is what free fall is, and a sinusoid -- whose",
        "; acceleration peaks at the apex and vanishes at the floor -- is exactly",
        "; backwards (SPEC.md Section 6.1).  Impact is the wrap p = 63 -> 0, not a",
        "; comparison against the floor.",
        ";",
        f"; y(0) = {table[0] / 256:g} (contact), y({P // 2}) = "
        f"{table[P // 2] / 256:g} (apex), y({P - 1}) = "
        f"{table[P - 1] / 256:g}.  The last frame before",
        f"; impact is {(table[0] - table[P - 1]) / 256:.4g} rasters above the "
        "floor, so the ball crosses that gap in",
        "; one frame: the contact speed SPEC.md Section 6.1 calls the visible "
        "tell.",
        ";",
        "; A draft of Section 6.1's sample table printed y(16) = 79.0 and "
        "y(24) = 57.5,",
        f"; where the formula gives {table[16] / 256:g} and "
        f"{table[24] / 256:g} and no single amplitude reproduces",
        "; both of the draft's numbers.  The formula won, and Section 6.1 now "
        "agrees;",
        "; see tools/gen_bounce.py.",
        "",
        '        .segment "RODATA"',
        "",
        "bounce_tab:",
    ]

    emitted = 0
    for p, v in enumerate(table):
        frac, integer = v & 0xFF, v >> 8
        lines.append(f"        .byte ${frac:02X}, ${integer:02X}"
                     f"          ; p = {p:2d}   y = {v / 256:8.4f}")
        emitted += 2
    lines.append("bounce_tab_end:")
    lines.append("")

    # --- asserts: fail loudly rather than emit something short -------------
    assert emitted == P * 2, f"emitted {emitted} bytes, expected {P * 2}"
    assert table[0] >> 8 == 158, f"y(0) integer is {table[0] >> 8}, expected 158"
    assert table[32] >> 8 == 54, f"y(32) integer is {table[32] >> 8}, expected 54"
    for k in range(1, 32):
        assert table[32 - k] == table[32 + k], \
            f"table is not symmetric about p = 32 at k = {k}: " \
            f"{table[32 - k]} != {table[32 + k]}"
    for p, v in enumerate(table):
        assert Y_MIN <= (v >> 8) <= Y_MAX, \
            f"y({p}) integer {v >> 8} is outside the sprite Y window " \
            f"{Y_MIN}-{Y_MAX}"

    out = Path(__file__).resolve().parent.parent / "bounce.inc"
    out.write_text("\n".join(lines))

    print(f"{out}: {emitted} bytes, {P} entries")
    print(f"y(0) = {table[0] / 256:.4f}  y(32) = {table[32] / 256:.4f}  "
          f"y(63) = {table[63] / 256:.4f}")
    print(f"integer range {min(v >> 8 for v in table)}-"
          f"{max(v >> 8 for v in table)} (window {Y_MIN}-{Y_MAX})")


if __name__ == "__main__":
    main()
