#!/usr/bin/env python3
"""bwv847.py -> reference scores for `c64 audio capture --ref`.

A score is the CLAIM; the capture is the check.  So it is written from the
arrangement, never from the transcription: pasting a transcription back in
"produces a diff that passes by construction -- with your bug baked in as the
specification" (references/audio-verification.md).

THE MODEL, which is the whole of the method.  Hand arithmetic
(rows x frames-per-row, one entry per notated note) is wrong, because what
the player does at a note boundary happens inside the frame grid and the
score describes the grid, not the sheet.  So:

  1. Model the player ONE FRAME AT A TIME -- emit the note name a
     once-per-frame sampler would read on that frame, or `rest`.
  2. Run-length encode that list.

That is the same algorithm the transcriber runs from the other side, so two
models of one grid agree by construction.

This player drops and re-raises the gate inside a single frame, so the
sampler never sees the gate low: there are no 1-frame rests to list, and two
consecutive equal pitches MERGE into one entry.  The run-length encoder gets
that for free.

    python3 genscore.py --list                 # the four capture windows
    python3 genscore.py --window entry1 --start-frame 238 -o out.yaml
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import bwv847  # noqa: E402
import genmusic  # noqa: E402

HOLD = 150
LEADIN = 88
MUSIC0 = HOLD + LEADIN          # frame of sixteenth 0
FPS16 = 8                       # frames per sixteenth
# How far BEFORE the moment to park.  Arming a capture spends ~155 emulated
# frames, so parking on the moment itself opens the window about a bar late
# and the entry the window is named for has already happened.  Measured: with
# a 30-frame pre-roll, entry3's window opened at bar 8 for a bass entry at bar
# 7.  The report passed anyway -- a score matches whatever is in the window --
# which is why this is checked by reading the roll, not by the verdict.
PREROLL = 200
NSIX = genmusic.NSIX


def per_frame(streams: list[list[int]], nframes: int) -> list[list[str]]:
    """One entry per frame per voice: what a once-per-frame sampler reads."""
    out: list[list[str]] = [[], [], []]
    for v in range(3):
        cur = "rest"
        for f in range(nframes):
            if f >= MUSIC0 and (f - MUSIC0) % FPS16 == 0:
                k = (f - MUSIC0) // FPS16
                if k >= NSIX:
                    cur = "rest"          # the piece has ended; gates released
                else:
                    b = streams[v][k]
                    if b == 0x00:
                        cur = "rest"
                    elif b != 0xFF:       # a hold leaves `cur` alone
                        cur = spell(b)
            out[v].append(cur)
    return out


def spell(byte: int) -> str:
    """The note name, spelled the way the arrangement spells it.

    The comparison is by pitch, not by string -- `Ab4`, `G#4` and `A♭4` are
    one note to the differ -- so the readable spelling costs nothing.
    """
    p = (byte & 31) - 1
    acc = (byte >> 5) & 3
    letter, octave = genmusic.LADDER[p]
    return f"{letter}{'#' if acc == 1 else 'b' if acc == 2 else ''}{octave}"


def rle(frames: list[str]) -> list[tuple[str, int]]:
    out: list[tuple[str, int]] = []
    for name in frames:
        if out and out[-1][0] == name:
            out[-1] = (name, out[-1][1] + 1)
        else:
            out.append((name, 1))
    return out


def score(start: int, length: int) -> str:
    streams = genmusic.expand()
    grid = per_frame(streams, start + length + 2)
    lines = [
        "# GENERATED by tools/genscore.py from tools/bwv847.py -- the claim,",
        "# not a transcription.  Regenerate rather than edit.",
        f"# window: frames {start}..{start + length - 1} of the program's own clock",
        "tempo_frames_per_row: 8",
        "voices:",
    ]
    for v in range(3):
        events = rle(grid[v][start:start + length])
        # Leading and trailing silence are exempt from the diff, so drop them
        # rather than claim a length for them.
        while events and events[0][0] == "rest":
            events.pop(0)
        while events and events[-1][0] == "rest":
            events.pop()
        lines.append(f"  {v + 1}:")
        if not events:
            lines[-1] = f"  {v + 1}: []"      # the positive claim: sits out
            continue
        for i, (name, n) in enumerate(events):
            first_and_running = i == 0 and grid[v][start - 1] == name if start else False
            last = i == len(events) - 1
            # The window's edges cut notes in half: omit `frames` where the
            # note was already sounding when the window opened, and on the
            # last entry, which the window closes mid-note.
            if first_and_running or last:
                lines.append(f"    - {{note: {name}}}")
            else:
                lines.append(f"    - {{note: {name}, frames: {n}}}")
    return "\n".join(lines) + "\n"


def pwm_at(frame: int) -> int:
    """The pulse width the program has written by machine frame `frame`.

    This is the alignment clock.  pwmtick runs only once the static hold is
    over -- `tick` returns early during HOLD, before muswrite -- so the sweep
    has stepped `frame - (HOLD - 1)` times by then.  The triangle is 128 steps
    up and 128 down, so the value pins a machine frame modulo 256, which is
    far wider than any lead-in.
    """
    v, d = 0x0400, 1
    for _ in range(max(0, frame - (HOLD - 1))):
        if d > 0:
            v += 16
            if (v >> 8) >= 0x0C:
                d = -1
        else:
            v -= 16
            if (v >> 8) < 0x04:
                d = 1
    return v


def align(log_path: str, guess: int, span: int = 120) -> int:
    """The machine frame the log's frame 0 actually is, measured not assumed.

    `lead_in_frames` is the capture's own estimate of how many emulated frames
    arming spent -- when it is available at all.  This demo runs no ROM code
    inside its interrupt, so the KERNAL jiffy the estimate is measured from
    never advances and the capture reports null; audio-evidence.sh substitutes
    the measured typical of 155.  Either way the estimate is only a starting
    point.  The search span is half the sweep's 256-frame period, so the guess
    has to be within about 120 frames of the truth and the answer is then
    unique; the estimate is comfortably inside that.  When it is available it
    is accurate to about a frame -- fine for a window
    that opens in silence, where the leading rest is exempt from the diff and
    absorbs the error, and not fine for one that opens mid-phrase, where being
    two frames out shifts every event against the score.

    So read it off the recording instead.  The log samples $D400-$D418 once a
    frame, and $D402/$D403 carry voice 1's pulse width, which the program
    sweeps on a 256-frame triangle.  Matching the log's first sample against
    the modelled sweep gives the window's true start.  This uses no pitch
    information at all, so it cannot launder a wrong note into a passing
    score: it fixes WHERE the window is, and the diff still decides WHAT is in
    it.
    """
    import json
    with open(log_path) as fh:
        fh.readline()                      # the clock stamp on line 1
        first = json.loads(fh.readline())
    want = first["regs"][2] | (first["regs"][3] << 8)
    # The triangle is SYMMETRIC, so a pulse width matches once on the way up
    # and once on the way down; a value alone is ambiguous and picking the
    # candidate nearest the estimate picks wrong about half the time.  It did:
    # the first version of this chose 1533 where the truth was 1613, and the
    # score came out ten sixteenths early.  Take the sweep's DIRECTION from a
    # second log frame and require the candidate to match that too, which
    # makes the answer unique inside the 256-frame period.
    second = json.loads(open(log_path).read().splitlines()[2])
    rising = (second["regs"][2] | (second["regs"][3] << 8)) > want
    hits = [f for f in range(max(1, guess - span), guess + span)
            if pwm_at(f) == want and (pwm_at(f + 1) > want) == rising]
    if not hits:
        raise SystemExit(
            f"align: no machine frame within {span} of {guess} has pulse width "
            f"${want:04x} on a {'rising' if rising else 'falling'} sweep; the "
            f"model and the program disagree")
    return min(hits, key=lambda f: abs(f - guess))


def windows() -> list[tuple[str, int, int]]:
    """(name, start frame, length in frames) for the four structural moments."""
    out = []
    seen = set()
    for bar, slot, voice, label in bwv847.SUBJECT_ENTRIES:
        if voice in seen or len(seen) >= 3:
            continue
        seen.add(voice)
        k = bar * 16 + slot
        out.append((f"entry{len(seen)}", max(0, MUSIC0 + k * FPS16 - PREROLL),
                    12 * 60))
    p0 = bwv847.PEDAL[0]        # 0-based bar index
    out.append(("pedal", MUSIC0 + p0 * 16 * FPS16 - PREROLL, 14 * 60))
    return out


def shot_points() -> list[tuple[str, int, int]]:
    """(name, 0-based bar, slot) for each evidence screenshot that needs a
    musical moment.  Derived from the arrangement so the script and the score
    cannot drift apart."""
    out: list[tuple[str, int, int]] = []
    seen: set[int] = set()
    for bar, slot, voice, _label in bwv847.SUBJECT_ENTRIES:
        if voice in seen or len(seen) >= 3:
            continue
        seen.add(voice)
        out.append((f"entry{len(seen)}", bar, slot))
    out.append(("pedal", bwv847.PEDAL[0], 0))   # PEDAL is 0-based already
    out.append(("crossing", *crossing_bar()))
    out.append(("accidental", *accidental_bar()))
    return out


def last_attack() -> int:
    streams = genmusic.expand()
    return max(k for k in range(NSIX) for v in range(3)
               if streams[v][k] not in (0x00, 0xFF))


def crossing_bar() -> tuple[int, int]:
    """The first sixteenth where voice 1 sounds BELOW voice 2 -- the frame the
    layout claim is about, found in the data instead of chosen by eye."""
    streams = genmusic.expand()
    live = [0, 0, 0]
    for k in range(NSIX):
        for v in range(3):
            b = streams[v][k]
            if b not in (0x00, 0xFF):
                live[v] = (b & 31) - 1
        # a LARGER ladder position is LOWER on the staff
        if live[0] and live[1] and live[0] > live[1]:
            return k // 16, k % 16
    return 0, 0


def accidental_bar() -> tuple[int, int]:
    """The first sixteenth carrying an accidental on a repeated letter name --
    the case that justifies giving accidentals their own column."""
    streams = genmusic.expand()
    prev = [None, None, None]
    for k in range(NSIX):
        for v in range(3):
            b = streams[v][k]
            if b in (0x00, 0xFF):
                continue
            p, acc = (b & 31) - 1, (b >> 5) & 3
            if acc and prev[v] is not None and prev[v] == p:
                return k // 16, k % 16
            prev[v] = p
    for k in range(NSIX):
        for v in range(3):
            b = streams[v][k]
            if b not in (0x00, 0xFF) and (b >> 5) & 3:
                return k // 16, k % 16
    return 0, 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--shots", action="store_true",
                    help="print `name frame` pairs for tools/evidence.sh")
    ap.add_argument("--start-frame", type=int)
    ap.add_argument("--align-log", help="sid-log.jsonl to measure the window "
                                        "start from, instead of trusting it")
    ap.add_argument("--frames", type=int, default=720)
    ap.add_argument("-o", "--out")
    a = ap.parse_args()
    if a.shots:
        # The frames the evidence protocol parks on, derived from the
        # arrangement rather than written down twice.
        shots = [(name, MUSIC0 + (bar * 16 + slot) * FPS16)
                 for name, bar, slot in shot_points()]
        # The scroll halts when the LAST ATTACK's head reaches the now column,
        # at shifts = 22 + 2k; the chord then rings there until the sequencer
        # releases it 8 sixteenths later.  Shoot inside that gap, where the
        # picture is stopped and the chord is still sounding and backlit.
        halt = HOLD + 4 * (22 + 2 * last_attack()) + 16
        shots.append(("fine", halt))
        # SORTED.  The script walks forward only -- `until` cannot rewind --
        # so an out-of-order list silently captures later shots at whatever
        # frame the previous one left behind.  It did: `accidental` and
        # `crossing` came after `pedal` and both came out as an empty staff.
        for name, frame in sorted(shots, key=lambda t: t[1]):
            print(f"{name} {frame}")
        return 0
    if a.list:
        for name, start, length in windows():
            print(f"{name}\tstart_frame={start}\tframes={length}"
                  f"\tseconds={length / 60.0:.1f}")
        return 0
    if a.start_frame is None:
        ap.error("--start-frame is required unless --list")
    start = a.start_frame
    if a.align_log:
        start = align(a.align_log, a.start_frame)
        print(f"aligned: log frame 0 is machine frame {start} "
              f"(estimate was {a.start_frame})", file=sys.stderr)
    text = score(start, a.frames)
    if a.out:
        Path(a.out).write_text(text)
        print(f"wrote {a.out}")
    else:
        print(text, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
