"""Build Commodore 64 cartridge images from ca65 sources and .prg files.

Three author models share one pipeline: assemble into a ROM-address linker
config, pad the result to the exact size cartconv demands, convert. The boot
stub is generated unless the author supplies their own STARTUP segment.

Everything about *how a cartridge boots* is measured, not assumed:
8K/16K carts boot through the CBM80 signature the KERNAL reset scans for at
$8004; Ultimax and EasyFlash carts have no KERNAL to scan, so they boot
through the CPU reset vector at $FFFC.
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

import yaml

from .basic import tokenize
from .build import BuildError, _find_tool, _parse_deps, _run, build_asm
from .cartridge import (
    BANK_WINDOW,
    CRT_NAME_LEN,
    EF_IMAGE_BYTES,
    EF_MAX_BANKS,
    CartError,
    bin_to_crt,
    get_cart_type,
)
from .machines import get_profile
from .symbols import parse_labels, save_labels

# Cart geometry, all $2000-aligned windows.
ROML_START = 0x8000
ROMH_START = 0xA000
ULTIMAX_START = 0xE000
VECTORS_ADDR = 0xFFFA
VECTORS_SIZE = 6

# Where a cartridge's mutable state lives. $0800 is the first byte the boot
# stub does not clobber: RAMTAS clears $0002-$0101 and $0200-$03FF, and CINT
# clears the $0400-$07FF screen. The area stops below the cart window at $8000.
RAM_START = 0x0800
RAM_SIZE = 0x7800                     # $0800-$7FFF
# An Ultimax cartridge only has RAM at $0000-$0FFF — everything else is open
# bus or cart ROM — so BSS gets the $0800-$0FFF half of it.
ULTIMAX_RAM_SIZE = 0x0800

_ZP = "    ZP:   start = $0000, size = $0100;"
_SEG_COMMON = """\
    ZEROPAGE: load = ZP,   type = zp, optional = yes;
    STARTUP:  load = {rom}, type = ro, optional = yes;
    CODE:     load = {rom}, type = ro;
    RODATA:   load = {rom}, type = ro, optional = yes;
    DATA:     load = {rom}, type = ro, optional = yes;
    BSS:      load = RAM,  type = bss, optional = yes, define = yes;"""


def _ram_area(size: int) -> str:
    """A RAM memory area for BSS. No `file` attribute: it is address space
    only and must never contribute bytes to the ROM image."""
    return f"    RAM:  start = ${RAM_START:04X}, size = ${size:04X}, define = yes;"


def cart_linker_config(cart_type: str) -> str:
    """ld65 config placing code in ROM windows instead of at the BASIC start.

    DATA is `type = ro`: a cartridge's data segment lives in ROM and cannot be
    written. Mutable state belongs in BSS, which every config maps to a RAM
    area — see RAM_START — so `.segment "BSS"` links without further setup.
    """
    get_cart_type(cart_type)        # raises CartError naming the known types
    if cart_type == "8k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"{_ram_area(RAM_SIZE)}\n"
            f"    ROM:  file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "}\n"
        )
    if cart_type == "16k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"{_ram_area(RAM_SIZE)}\n"
            f"    ROML: file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            f"    ROMH: file = %O, start = ${ROMH_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROML')}\n"
            "    ROMH:     load = ROMH, type = ro, optional = yes;\n"
            "}\n"
        )
    if cart_type == "ultimax":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"{_ram_area(ULTIMAX_RAM_SIZE)}\n"
            f"    ROM:  file = %O, start = ${ULTIMAX_START:04X}, "
            f"size = ${BANK_WINDOW - VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            f"    VEC:  file = %O, start = ${VECTORS_ADDR:04X}, "
            f"size = ${VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "    VECTORS:  load = VEC,  type = ro;\n"
            "}\n"
        )
    raise CartError(
        f"{cart_type!r} has no single-region linker config; use `cart build` "
        "with an EasyFlash manifest instead")


# The reset stub an 8K/16K cartridge boots through. $8000-$8001 is the cold
# vector, $8002-$8003 the warm/NMI vector, $8004-$8008 the signature the
# KERNAL reset routine scans for. Without the signature the machine silently
# boots to BASIC (measured).
_CBM80_STUB = """\
; Generated by c64-tools — 8K/16K cartridge boot stub.
.import cart_main
.segment "STARTUP"
        .word   _cart_cold              ; $8000 cold vector
        .word   _cart_cold              ; $8002 warm/NMI vector
        .byte   $C3,$C2,$CD,$38,$30     ; "CBM80" — the KERNAL scans for this
_cart_cold:
        sei
        cld
        ldx     #$FF
        txs
        jsr     $FDA3                   ; IOINIT  — CIAs, VIC, IRQ timer
        jsr     $FD50                   ; RAMTAS  — clears $0002-$0101, $0200-$03FF
        jsr     $FD15                   ; RESTOR  — KERNAL vectors to $0314
        jsr     $FF5B                   ; CINT    — VIC + screen editor
        cli
        jmp     cart_main
"""

# An Ultimax cartridge replaces the KERNAL, so there is nothing to call and no
# CBM80 scan: the CPU takes RESET straight from $FFFC.
_ULTIMAX_STUB = """\
; Generated by c64-tools — Ultimax cartridge boot stub.
; There is no KERNAL under an Ultimax cart: cart_main owns all hardware init,
; and only $0000-$0FFF is RAM.
.import cart_main
.segment "STARTUP"
_cart_reset:
        sei
        cld
        ldx     #$FF
        txs
        jmp     cart_main
.segment "VECTORS"
        .word   _cart_reset             ; $FFFA NMI
        .word   _cart_reset             ; $FFFC RESET
        .word   _cart_reset             ; $FFFE IRQ/BRK
"""


def boot_stub_source(cart_type: str) -> str:
    if cart_type in ("8k", "16k"):
        return _CBM80_STUB
    if cart_type == "ultimax":
        return _ULTIMAX_STUB
    raise CartError(f"no boot stub for cartridge type {cart_type!r}")


_STARTUP_RE = re.compile(r'^\s*\.segment\s+"STARTUP"', re.MULTILINE)


def has_own_startup(sources) -> bool:
    """True when the author supplies their own STARTUP segment — the opt-out.

    Scanned over the source and everything ca65 reports it included, so an
    author can keep their boot code in a shared .inc.
    """
    for src in sources:
        try:
            text = Path(src).read_text()
        except (OSError, UnicodeDecodeError):
            continue
        # Strip line comments so a mention in prose does not count.
        text = re.sub(r";.*$", "", text, flags=re.MULTILINE)
        if _STARTUP_RE.search(text):
            return True
    return False


def cart_title(raw: str) -> str:
    """Normalize a cartridge name for the 32-byte .crt name field."""
    t = str(raw).upper().strip()
    if not t:
        raise CartError("cartridge title is empty")
    if len(t) > CRT_NAME_LEN:
        raise CartError(
            f"title {t!r} is {len(t)} chars; the .crt name field holds "
            f"{CRT_NAME_LEN}")
    if not all(0x20 <= ord(c) <= 0x7E for c in t):
        raise CartError(f"title {t!r} has characters outside printable ASCII")
    return t


def _assemble(ca65: str, source: Path, obj: Path, dep: Path) -> tuple[Path, ...]:
    _run([ca65, "-g", str(source), "-o", str(obj), "--create-dep", str(dep)])
    return _parse_deps(dep, fallback=Path(source))


def _run_hint(crt: Path) -> str:
    return f"x64sc -ntsc -cartcrt {crt}"


def build_cart(source, out=None, cart_type: str = "8k",
               title: str | None = None) -> dict:
    """Assemble a cart-native .s into a bootable .crt.

    A boot stub is injected unless the source (or something it includes)
    defines its own STARTUP segment, in which case the author owns the boot
    sequence and must place the CBM80 header / reset vectors themselves.

    The padded raw ROM image is kept beside the .crt (same stem, `.bin`), the
    way build_asm keeps its label file: it is what a flasher or an emulator's
    raw-ROM mode wants, and regenerating it means re-running the whole build.
    """
    ct = get_cart_type(cart_type)
    if ct.max_banks > 1:
        raise CartError(
            f"{cart_type} is bank-switched; build it from a manifest with "
            "`c64 cart build game.ef.yaml`")
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")
    source = Path(source)
    crt = Path(out) if out is not None else source.with_suffix(".crt")
    labels = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    name = cart_title(title if title is not None else source.stem)
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        obj, dep = td / f"{source.stem}.o", td / "deps.d"
        deps = _assemble(ca65, source, obj, dep)
        objs = [str(obj)]
        if not has_own_startup(deps):
            stub_src = td / "_cartboot.s"
            stub_src.write_text(boot_stub_source(cart_type))
            stub_obj = td / "_cartboot.o"
            _run([ca65, str(stub_src), "-o", str(stub_obj)])
            objs.append(str(stub_obj))
        cfg = td / "cart.cfg"
        cfg.write_text(cart_linker_config(cart_type))
        try:
            _run([ld65, "-o", str(raw), "-C", str(cfg), "-Ln", str(labels), *objs])
        except BuildError as e:
            if "cart_main" in str(e):
                raise CartError(
                    f"{source}: the generated boot stub jumps to `cart_main`, "
                    "but the source does not export it. Add "
                    "`.export cart_main` (or supply your own STARTUP segment "
                    "to take over the boot sequence).\n" + str(e)
                ) from None
            raise
        # Ultimax parks its reset vectors in the last 6 bytes of the image.
        reserved = VECTORS_SIZE if ct.name == "ultimax" else 0
        used = _used_bytes(raw.read_bytes(), reserved)
        bin_to_crt(raw, crt, cart_type, name)
    return {"crt": str(crt), "bin": str(raw), "labels": str(labels),
            "title": name, "cart_type": cart_type, "run": _run_hint(crt),
            "bytes": used, "free": ct.image_bytes - used}


def _used_bytes(image: bytes, reserved_tail: int = 0) -> int:
    """Bytes before the $FF fill tail — what the author actually spent.

    Measured per $2000 window, because each window is padded independently: a
    16K image is ROML followed by ROMH, so a single byte of ROMH data sits
    after ~8 KB of ROML fill. Scanning the concatenated image as one block
    would charge the author for that fill.

    `reserved_tail` is a fixed always-occupied region at the end of the image
    (the Ultimax reset vectors at $FFFA). Those bytes are never $FF, so the
    fill heuristic has to stop short of them and count them separately —
    otherwise every Ultimax cart reports as completely full.
    """
    body = image[:len(image) - reserved_tail] if reserved_tail else image
    used = sum(len(body[i:i + BANK_WINDOW].rstrip(b"\xFF"))
               for i in range(0, len(body), BANK_WINDOW))
    return used + reserved_tail


# A wrapped program is copied out of ROM to its load address, then started.
# The BASIC path is the measured `RUN` equivalent: init the BASIC vectors and
# zero page, point VARTAB/ARYTAB/STREND past the program, CLR, then hand
# control to the interpreter loop.
_LAUNCHER = """\
; Generated by c64-tools — launcher cartridge wrapping a .prg.
.segment "STARTUP"
        .word   _cart_cold
        .word   _cart_cold
        .byte   $C3,$C2,$CD,$38,$30     ; "CBM80"
_cart_cold:
        sei
        cld
        ldx     #$FF
        txs
        jsr     $FDA3                   ; IOINIT
        jsr     $FD50                   ; RAMTAS
        jsr     $FD15                   ; RESTOR
        jsr     $FF5B                   ; CINT
        cli
{basic_init}\
        lda     #<_blob                 ; copy the embedded image down
        sta     $FB
        lda     #>_blob
        sta     $FC
        lda     #<${load_addr:04X}
        sta     $FD
        lda     #>${load_addr:04X}
        sta     $FE
        ldx     #_PAGES
        ldy     #$00
_page:  lda     ($FB),y
        sta     ($FD),y
        iny
        bne     _page
        inc     $FC
        inc     $FE
        dex
        bne     _page
{start}\
_blob:  .incbin "{prg_name}", 2         ; skip the 2-byte load address
_blob_end:
_PAGES  = (_blob_end - _blob + 255) / 256
"""

_BASIC_INIT = """\
        jsr     $E453                   ; BASIC vectors -> $0300
        jsr     $E3BF                   ; BASIC zero-page pointers
"""

_BASIC_START = """\
        lda     #<${prog_end:04X}       ; VARTAB / ARYTAB / STREND
        sta     $2D
        sta     $2F
        sta     $31
        lda     #>${prog_end:04X}
        sta     $2E
        sta     $30
        sta     $32
        jsr     $A659                   ; CLR
        jmp     $A7AE                   ; BASIC interpreter loop = RUN
"""

_ML_START = """\
        jmp     ${load_addr:04X}
"""


def launcher_source(load_addr: int, prog_end: int, kind: str,
                    prg_name: str = "wrapped.prg") -> str:
    if kind == "basic":
        basic_init, start = _BASIC_INIT, _BASIC_START.format(prog_end=prog_end)
    elif kind == "ml":
        basic_init, start = "", _ML_START.format(load_addr=load_addr)
    else:
        raise CartError(f"unknown wrap kind {kind!r} (use 'basic' or 'ml')")
    return _LAUNCHER.format(basic_init=basic_init, start=start,
                            load_addr=load_addr, prg_name=prg_name)


def wrap_prg(source, out=None, cart_type: str = "8k", title: str | None = None,
             model: str = "c64") -> dict:
    """Wrap an existing program in a launcher cartridge.

    `.bas` is tokenized first and `.s` assembled first, so any program this
    toolchain can build becomes a boot cartridge. The wrapped image is stored
    in ROM after the launcher and copied to its load address at boot.
    """
    if cart_type == "ultimax":
        raise CartError(
            "wrap-a-prg chains through the KERNAL and BASIC, and an Ultimax "
            "cartridge replaces them; use --cart-type 8k or 16k")
    ct = get_cart_type(cart_type)
    if ct.max_banks > 1:
        raise CartError(f"cannot wrap a .prg into a {cart_type} cartridge")
    source = Path(source)
    crt = Path(out) if out is not None else source.with_suffix(".crt")
    labels = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    name = cart_title(title if title is not None else source.stem)
    profile = get_profile(model)
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        ext = source.suffix.lower()
        if ext == ".prg":
            prg = source
            kind = "basic" if _looks_like_basic(source, profile.basic_start) else "ml"
        elif ext == ".bas":
            prg = tokenize(source, td / "wrapped.prg", profile.basic_version)
            kind = "basic"
        elif ext == ".s":
            prg = build_asm(source, out_prg=td / "wrapped.prg",
                            basic_start=profile.basic_start).prg
            kind = "ml"
        else:
            raise CartError(
                f"cannot wrap {ext or source.name!r} (use .prg, .bas, or .s)")

        image = Path(prg).read_bytes()
        if len(image) < 3:
            raise CartError(
                f"{prg}: {len(image)} bytes — too short to hold a 2-byte load "
                "address and a program")
        load_addr = int.from_bytes(image[:2], "little")
        body = image[2:]
        prog_end = load_addr + len(body)

        budget = ct.image_bytes
        if len(body) + 256 > budget:            # 256 ≈ the launcher's own size
            nxt = "16k" if cart_type == "8k" else None
            hint = (f"; retry with --cart-type {nxt}" if nxt
                    else "; use the native or EasyFlash path")
            raise CartError(
                f"{source}: the program is {len(body)} bytes and will not fit "
                f"a {cart_type} cartridge ({budget} bytes){hint}")

        blob = td / "wrapped.prg"
        if Path(prg).resolve() != blob.resolve():
            blob.write_bytes(image)
        src_path = td / "_launcher.s"
        src_path.write_text(launcher_source(load_addr, prog_end, kind, blob.name))
        obj = td / "_launcher.o"
        _run([ca65, str(src_path), "-o", str(obj), "-I", str(td),
              "--bin-include-dir", str(td)])
        cfg = td / "cart.cfg"
        cfg.write_text(cart_linker_config(cart_type))
        try:
            _run([ld65, "-o", str(raw), "-C", str(cfg), "-Ln", str(labels),
                  str(obj)])
        except BuildError as e:
            if "range" in str(e).lower() or "overflow" in str(e).lower():
                nxt = "16k" if cart_type == "8k" else None
                hint = (f"; retry with --cart-type {nxt}" if nxt else
                        "; a program this large needs the native or EasyFlash path")
                raise CartError(
                    f"{source}: the wrapped program ({len(body)} bytes) plus the "
                    f"launcher does not fit a {cart_type} cartridge"
                    f"{hint}\n{e}") from None
            raise
        used = _used_bytes(raw.read_bytes())
        bin_to_crt(raw, crt, cart_type, name)

    return {"crt": str(crt), "bin": str(raw), "labels": str(labels),
            "title": name, "cart_type": cart_type, "run": _run_hint(crt),
            "bytes": used, "free": ct.image_bytes - used,
            "wrapped": str(source), "load_addr": load_addr, "kind": kind}


def _looks_like_basic(prg: Path, basic_start: int) -> bool:
    """A .prg loading at the BASIC start is treated as a BASIC program."""
    head = prg.read_bytes()[:2]
    return len(head) == 2 and int.from_bytes(head, "little") == basic_start


# --- EasyFlash ------------------------------------------------------------
#
# Measured geometry: 64 banks x 16 KB, each bank a $8000 LOROM window and an
# $A000 HIROM window that switch *together* on a write to $DE00. cartconv
# accepts only a full 1 MB raw image and drops all-$FF windows itself, so a
# sparse manifest costs nothing in the finished .crt.
#
# A cartridge powers up in Ultimax mode and the CPU takes RESET from $FFFC,
# which is offset $1FFC of bank 0's HIROM window — so the boot code lives in
# bank 0 HI assembled for $E000, not in bank 0 LO behind a CBM80 header.

EF_JUMPTABLE = 0x9F00        # every code bank's entry table
EF_RESIDENT = 0x0900         # RAM the trampoline runs from
EF_MODE_16K = 0x87           # $DE02 value that leaves Ultimax for 16K mode
EF_WINDOWS = ("lo", "hi")
_EF_CODE_EXT = ".s"
_EF_JT_SIZE = 0x0100                        # the reserved page at $9F00
_EF_LO_BODY = EF_JUMPTABLE - ROML_START     # $8000-$9EFF, the author's part


def ef_window_config(window: str, boot: bool = False) -> str:
    """ld65 config for one EasyFlash window.

    The LOROM window reserves its top page for the jump table at $9F00: banks
    are linked independently, so a fixed table is the only stable way for one
    bank to call into another. The boot window additionally runs a RESIDENT
    segment from RAM — $E000 stops existing the moment the cart leaves Ultimax
    mode, so the code that switches modes must already be somewhere else.

    $0900 is that somewhere: in Ultimax mode only $0000-$0FFF is RAM, RAMTAS
    clears $0002-$0101 and $0200-$03FF, and CINT clears the screen at
    $0400-$07FF. All three constraints were measured.
    """
    if window not in EF_WINDOWS:
        raise CartError(f"window must be 'lo' or 'hi', not {window!r}")
    if window == "lo":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ROML_START:04X}, size = $1F00, "
            "fill = yes, fillval = $FF;\n"
            f"    JT:   file = %O, start = ${EF_JUMPTABLE:04X}, size = $0100, "
            "fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            "    ZEROPAGE: load = ZP,  type = zp, optional = yes;\n"
            "    CODE:     load = ROM, type = ro;\n"
            "    RODATA:   load = ROM, type = ro, optional = yes;\n"
            "    DATA:     load = ROM, type = ro, optional = yes;\n"
            "    JUMPTAB:  load = JT,  type = ro, optional = yes;\n"
            "}\n"
        )
    if not boot:
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ROMH_START:04X}, size = $2000, "
            "fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            "    ZEROPAGE: load = ZP,  type = zp, optional = yes;\n"
            "    CODE:     load = ROM, type = ro;\n"
            "    RODATA:   load = ROM, type = ro, optional = yes;\n"
            "    DATA:     load = ROM, type = ro, optional = yes;\n"
            "}\n"
        )
    return (
        "MEMORY {\n"
        f"{_ZP}\n"
        f"    RESIDENT: start = ${EF_RESIDENT:04X}, size = $0700;\n"
        f"    ROM:  file = %O, start = ${ULTIMAX_START:04X}, size = $1FFA, "
        "fill = yes, fillval = $FF;\n"
        f"    VEC:  file = %O, start = ${VECTORS_ADDR:04X}, "
        f"size = ${VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
        "}\n"
        "SEGMENTS {\n"
        "    ZEROPAGE: load = ZP,  type = zp, optional = yes;\n"
        "    STARTUP:  load = ROM, type = ro, optional = yes;\n"
        "    CODE:     load = ROM, type = ro;\n"
        "    RODATA:   load = ROM, type = ro, optional = yes;\n"
        "    RAMCODE:  load = ROM, run = RESIDENT, type = ro, define = yes;\n"
        "    VECTORS:  load = VEC, type = ro;\n"
        "}\n"
    )


_EF_BOOT_STUB = """\
; Generated by c64-tools — EasyFlash boot window (bank 0 HIROM at $E000).
; An EasyFlash cart powers up in Ultimax mode, so the CPU takes RESET from
; $FFFC here — there is no KERNAL and no CBM80 scan.
.include "cart.inc"
.segment "VECTORS"
        .word   ef_boot                 ; $FFFA NMI
        .word   ef_boot                 ; $FFFC RESET
        .word   ef_boot                 ; $FFFE IRQ/BRK
"""


def ef_boot_stub_source() -> str:
    return _EF_BOOT_STUB


def cart_include_dir() -> Path:
    """Directory holding cart.inc, shipped as package data."""
    return Path(__file__).parent / "data" / "cart"


def load_manifest(path) -> dict:
    """Parse an EasyFlash bank manifest, resolving every file against it."""
    path = Path(path)
    try:
        raw = yaml.safe_load(path.read_text())
    except yaml.YAMLError as e:
        raise CartError(f"{path}: {e}") from None
    if not isinstance(raw, dict):
        raise CartError(f"{path}: manifest must be a YAML mapping")
    name = cart_title(raw.get("name") or path.stem.replace(".ef", ""))
    banks_raw = raw.get("banks")
    if not isinstance(banks_raw, dict) or not banks_raw:
        raise CartError(f"{path}: manifest needs a non-empty `banks:` mapping")
    banks: dict[int, dict[str, Path]] = {}
    for key, windows in banks_raw.items():
        try:
            bank = int(key)
        except (TypeError, ValueError):
            raise CartError(f"{path}: bank key {key!r} is not a number") from None
        if not 0 <= bank < EF_MAX_BANKS:
            raise CartError(
                f"{path}: bank {bank} is outside the EasyFlash range "
                f"(0-{EF_MAX_BANKS - 1})")
        if not isinstance(windows, dict):
            raise CartError(
                f"{path}: bank {bank} must be a mapping like {{lo: f.s, hi: g.bin}}")
        unknown = sorted(set(windows) - set(EF_WINDOWS))
        if unknown:
            raise CartError(
                f"{path}: bank {bank} has unknown window(s) {unknown} "
                f"(use {' and '.join(EF_WINDOWS)})")
        resolved: dict[str, Path] = {}
        for window, filename in windows.items():
            f = (path.parent / str(filename)).resolve()
            if not f.exists():
                raise CartError(
                    f"{path}: bank {bank} {window} references {filename}, "
                    f"which does not exist")
            resolved[window] = f
        banks[bank] = resolved
    if "hi" not in banks.get(0, {}):
        raise CartError(
            f"{path}: an EasyFlash cartridge boots from the reset vector in "
            "bank 0 hi, so the manifest must give bank 0 a `hi:` window")
    return {"name": name, "banks": banks, "path": path}


def fill_table(windows: dict[tuple[int, str], int]) -> str:
    """Per-bank fill report. Always printed: silent overflow is the failure
    mode this exists to make impossible to miss."""
    lines = []
    total = 0
    for bank in sorted({b for b, _ in windows}):
        cells = []
        for window in EF_WINDOWS:
            used = windows.get((bank, window))
            if used is None:
                cells.append(f"{window.upper()}    ----          ")
                continue
            total += used
            cells.append(
                f"{window.upper()} {used:5,}/{BANK_WINDOW:5,} "
                f"({BANK_WINDOW - used:5,} free)")
        lines.append(f"bank {bank:02d}  " + "  ".join(cells))
    banks = len({b for b, _ in windows})
    lines.append(
        f"total {total:,} / {EF_IMAGE_BYTES:,} bytes across {banks} bank(s)")
    return "\n".join(lines)


def merge_bank_labels(per_window: dict[tuple[int, str], Path], out: Path) -> Path:
    """Merge each window's .lbl into one, tagging every symbol with its bank.

    Five banks all place code at $8000, so a bare symbol table is ambiguous.
    Prefixing (`b01lo_update`) keeps every existing consumer — `break add`,
    `disasm`, `until`, `symbols.nearest()` — working unchanged, and a
    breakpoint report already reads `$8000 (b01lo_update)`.
    """
    merged: dict[str, int] = {}
    for (bank, window), lbl in sorted(per_window.items()):
        if lbl is None or not Path(lbl).exists():
            continue
        for name, addr in parse_labels(Path(lbl).read_text()).items():
            if name.startswith("__") and name.endswith("__"):
                continue        # linker internals, not author symbols
            merged[f"b{bank:02d}{window}_{name}"] = addr
    save_labels(out, merged)
    return out


def _ef_window_used(data: bytes, window: str, boot: bool) -> int:
    """Bytes spent in one EasyFlash window.

    Each window is really several independently fill-padded regions, and
    _used_bytes' contract — rstrip the fill, then add an always-occupied tail —
    is what keeps the report honest for all of them:

    * the boot window ends with the reset vectors at $FFFA, which are never
      $FF, so they are a reserved tail rather than data (the same correction
      `build_cart` makes for Ultimax);
    * a LOROM window is a $1F00 body plus the reserved jump-table page at
      $9F00, padded apart, so one JUMPTAB entry must not charge the author for
      the ~7.7 KB of fill in front of it.
    """
    if boot:
        return _used_bytes(data, VECTORS_SIZE)
    if window == "lo" and len(data) > _EF_LO_BODY:
        return (_used_bytes(data[:_EF_LO_BODY])
                + _used_bytes(data[_EF_LO_BODY:]))
    return _used_bytes(data)


def build_easyflash(manifest_path, out=None) -> dict:
    """Assemble a multi-bank EasyFlash .crt from a manifest.

    Every `.s` window is linked independently against the window's own config;
    every other file is included verbatim. Overflow is a hard error naming the
    bank, window and overflow amount — never a silent truncation.

    The padded 1 MB raw image is kept beside the .crt (same stem, `.bin`), the
    way `build_cart` keeps its own: it is what a flasher or an emulator's
    raw-ROM mode wants, and regenerating it means re-running the whole build.
    """
    spec = load_manifest(manifest_path)
    manifest = spec["path"]
    crt = Path(out) if out is not None else manifest.with_suffix("").with_suffix(".crt")
    labels_out = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")

    image = bytearray(b"\xFF" * EF_IMAGE_BYTES)
    used: dict[tuple[int, str], int] = {}
    per_window_labels: dict[tuple[int, str], Path] = {}

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        for bank in sorted(spec["banks"]):
            for window in EF_WINDOWS:
                src = spec["banks"][bank].get(window)
                if src is None:
                    continue
                boot = (bank == 0 and window == "hi")
                if src.suffix.lower() == _EF_CODE_EXT:
                    data, lbl = _link_ef_window(
                        ca65, ld65, td, src, bank, window, boot)
                    per_window_labels[(bank, window)] = lbl
                else:
                    data = src.read_bytes()
                if len(data) > BANK_WINDOW:
                    raise CartError(
                        f"{manifest}: bank {bank} {window} ({src.name}) is "
                        f"{len(data):,} bytes — {len(data) - BANK_WINDOW:,} over "
                        f"the {BANK_WINDOW:,}-byte window")
                used[(bank, window)] = _ef_window_used(data, window, boot)
                off = bank * 2 * BANK_WINDOW + (0 if window == "lo" else BANK_WINDOW)
                image[off:off + len(data)] = data
        raw.write_bytes(bytes(image))
        bin_to_crt(raw, crt, "easyflash", spec["name"])
        # Inside the temp dir: every per-window .lbl ld65 wrote lives there and
        # is deleted the moment this block exits.
        merge_bank_labels(per_window_labels, labels_out)

    total = sum(used.values())
    return {"crt": str(crt), "bin": str(raw), "labels": str(labels_out),
            "title": spec["name"], "cart_type": "easyflash",
            "run": _run_hint(crt), "banks": sorted(spec["banks"]),
            "windows": {f"{b}{w}": n for (b, w), n in sorted(used.items())},
            "fill": fill_table(used), "bytes": total,
            "free": EF_IMAGE_BYTES - total}


def _link_ef_window(ca65: str, ld65: str, td: Path, src: Path, bank: int,
                    window: str, boot: bool) -> tuple[bytes, Path]:
    tag = f"b{bank:02d}{window}"
    obj, dep = td / f"{tag}.o", td / f"{tag}.d"
    inc = cart_include_dir()
    _run([ca65, "-g", str(src), "-o", str(obj), "--create-dep", str(dep),
          "-I", str(src.parent), "-I", str(inc)])
    deps = _parse_deps(dep, fallback=src)
    objs = [str(obj)]
    if boot and not has_own_startup(deps):
        stub = td / f"{tag}_boot.s"
        stub.write_text(ef_boot_stub_source())
        stub_obj = td / f"{tag}_boot.o"
        _run([ca65, str(stub), "-o", str(stub_obj), "-I", str(inc)])
        objs.append(str(stub_obj))
    cfg = td / f"{tag}.cfg"
    cfg.write_text(ef_window_config(window, boot=boot))
    binout, lbl = td / f"{tag}.bin", td / f"{tag}.lbl"
    _run([ld65, "-o", str(binout), "-C", str(cfg), "-Ln", str(lbl), *objs])
    return binout.read_bytes(), lbl
