"""Build Commodore 64 cartridge images from ca65 sources and .prg files.

Three author models share one pipeline: assemble into a ROM-address linker
config, pad the result to the exact size cartconv demands, convert. The boot
stub is generated unless the author supplies their own STARTUP segment.

Everything about *how a cartridge boots* is measured, not assumed:
8K/16K carts boot through the CBM80 signature the KERNAL reset scans for at
$8004; Ultimax and EasyFlash carts have no KERNAL to scan, so they boot
through the CPU reset vector at $FFFC.
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

from .build import BuildError, _find_tool, _parse_deps, _run
from .cartridge import (
    BANK_WINDOW,
    CRT_NAME_LEN,
    CartError,
    bin_to_crt,
    get_cart_type,
)

# Cart geometry, all $2000-aligned windows.
ROML_START = 0x8000
ROMH_START = 0xA000
ULTIMAX_START = 0xE000
VECTORS_ADDR = 0xFFFA
VECTORS_SIZE = 6

_ZP = "    ZP:   start = $0000, size = $0100;"
_SEG_COMMON = """\
    ZEROPAGE: load = ZP,   type = zp, optional = yes;
    STARTUP:  load = {rom}, type = ro, optional = yes;
    CODE:     load = {rom}, type = ro;
    RODATA:   load = {rom}, type = ro, optional = yes;
    DATA:     load = {rom}, type = ro, optional = yes;"""


def cart_linker_config(cart_type: str) -> str:
    """ld65 config placing code in ROM windows instead of at the BASIC start.

    DATA is `type = ro`: a cartridge's data segment lives in ROM and cannot be
    written. Mutable state belongs in a BSS segment the author places in RAM.
    """
    get_cart_type(cart_type)        # raises CartError naming the known types
    if cart_type == "8k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "}\n"
        )
    if cart_type == "16k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROML: file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            f"    ROMH: file = %O, start = ${ROMH_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROML')}\n"
            "    ROMH:     load = ROMH, type = ro, optional = yes;\n"
            "}\n"
        )
    if cart_type == "ultimax":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ULTIMAX_START:04X}, "
            f"size = ${BANK_WINDOW - VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            f"    VEC:  file = %O, start = ${VECTORS_ADDR:04X}, "
            f"size = ${VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "    VECTORS:  load = VEC,  type = ro;\n"
            "}\n"
        )
    raise CartError(
        f"{cart_type!r} has no single-region linker config; use `cart build` "
        "with an EasyFlash manifest instead")


# The reset stub an 8K/16K cartridge boots through. $8000-$8001 is the cold
# vector, $8002-$8003 the warm/NMI vector, $8004-$8008 the signature the
# KERNAL reset routine scans for. Without the signature the machine silently
# boots to BASIC (measured).
_CBM80_STUB = """\
; Generated by c64-tools — 8K/16K cartridge boot stub.
.import cart_main
.segment "STARTUP"
        .word   _cart_cold              ; $8000 cold vector
        .word   _cart_cold              ; $8002 warm/NMI vector
        .byte   $C3,$C2,$CD,$38,$30     ; "CBM80" — the KERNAL scans for this
_cart_cold:
        sei
        cld
        ldx     #$FF
        txs
        jsr     $FDA3                   ; IOINIT  — CIAs, VIC, IRQ timer
        jsr     $FD50                   ; RAMTAS  — clears $0002-$0101, $0200-$03FF
        jsr     $FD15                   ; RESTOR  — KERNAL vectors to $0314
        jsr     $FF5B                   ; CINT    — VIC + screen editor
        cli
        jmp     cart_main
"""

# An Ultimax cartridge replaces the KERNAL, so there is nothing to call and no
# CBM80 scan: the CPU takes RESET straight from $FFFC.
_ULTIMAX_STUB = """\
; Generated by c64-tools — Ultimax cartridge boot stub.
; There is no KERNAL under an Ultimax cart: cart_main owns all hardware init,
; and only $0000-$0FFF is RAM.
.import cart_main
.segment "STARTUP"
_cart_reset:
        sei
        cld
        ldx     #$FF
        txs
        jmp     cart_main
.segment "VECTORS"
        .word   _cart_reset             ; $FFFA NMI
        .word   _cart_reset             ; $FFFC RESET
        .word   _cart_reset             ; $FFFE IRQ/BRK
"""


def boot_stub_source(cart_type: str) -> str:
    if cart_type in ("8k", "16k"):
        return _CBM80_STUB
    if cart_type == "ultimax":
        return _ULTIMAX_STUB
    raise CartError(f"no boot stub for cartridge type {cart_type!r}")


_STARTUP_RE = re.compile(r'^\s*\.segment\s+"STARTUP"', re.MULTILINE)


def has_own_startup(sources) -> bool:
    """True when the author supplies their own STARTUP segment — the opt-out.

    Scanned over the source and everything ca65 reports it included, so an
    author can keep their boot code in a shared .inc.
    """
    for src in sources:
        try:
            text = Path(src).read_text()
        except (OSError, UnicodeDecodeError):
            continue
        # Strip line comments so a mention in prose does not count.
        text = re.sub(r";.*$", "", text, flags=re.MULTILINE)
        if _STARTUP_RE.search(text):
            return True
    return False


def cart_title(raw: str) -> str:
    """Normalize a cartridge name for the 32-byte .crt name field."""
    t = str(raw).upper().strip()
    if not t:
        raise CartError("cartridge title is empty")
    if len(t) > CRT_NAME_LEN:
        raise CartError(
            f"title {t!r} is {len(t)} chars; the .crt name field holds "
            f"{CRT_NAME_LEN}")
    if not all(0x20 <= ord(c) <= 0x7E for c in t):
        raise CartError(f"title {t!r} has characters outside printable ASCII")
    return t


def _assemble(ca65: str, source: Path, obj: Path, dep: Path) -> tuple[Path, ...]:
    _run([ca65, "-g", str(source), "-o", str(obj), "--create-dep", str(dep)])
    return _parse_deps(dep, fallback=Path(source))


def _run_hint(crt: Path) -> str:
    return f"x64sc -ntsc -cartcrt {crt}"


def build_cart(source, out=None, cart_type: str = "8k",
               title: str | None = None) -> dict:
    """Assemble a cart-native .s into a bootable .crt.

    A boot stub is injected unless the source (or something it includes)
    defines its own STARTUP segment, in which case the author owns the boot
    sequence and must place the CBM80 header / reset vectors themselves.

    The padded raw ROM image is kept beside the .crt (same stem, `.bin`), the
    way build_asm keeps its label file: it is what a flasher or an emulator's
    raw-ROM mode wants, and regenerating it means re-running the whole build.
    """
    ct = get_cart_type(cart_type)
    if ct.max_banks > 1:
        raise CartError(
            f"{cart_type} is bank-switched; build it from a manifest with "
            "`c64 cart build game.ef.yaml`")
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")
    source = Path(source)
    crt = Path(out) if out is not None else source.with_suffix(".crt")
    labels = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    name = cart_title(title if title is not None else source.stem)
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        obj, dep = td / f"{source.stem}.o", td / "deps.d"
        deps = _assemble(ca65, source, obj, dep)
        objs = [str(obj)]
        if not has_own_startup(deps):
            stub_src = td / "_cartboot.s"
            stub_src.write_text(boot_stub_source(cart_type))
            stub_obj = td / "_cartboot.o"
            _run([ca65, str(stub_src), "-o", str(stub_obj)])
            objs.append(str(stub_obj))
        cfg = td / "cart.cfg"
        cfg.write_text(cart_linker_config(cart_type))
        try:
            _run([ld65, "-o", str(raw), "-C", str(cfg), "-Ln", str(labels), *objs])
        except BuildError as e:
            if "cart_main" in str(e):
                raise CartError(
                    f"{source}: the generated boot stub jumps to `cart_main`, "
                    "but the source does not export it. Add "
                    "`.export cart_main` (or supply your own STARTUP segment "
                    "to take over the boot sequence).\n" + str(e)
                ) from None
            raise
        # Ultimax parks its reset vectors in the last 6 bytes of the image.
        reserved = VECTORS_SIZE if ct.name == "ultimax" else 0
        used = _used_bytes(raw.read_bytes(), reserved)
        bin_to_crt(raw, crt, cart_type, name)
    return {"crt": str(crt), "bin": str(raw), "labels": str(labels),
            "title": name, "cart_type": cart_type, "run": _run_hint(crt),
            "bytes": used, "free": ct.image_bytes - used}


def _used_bytes(image: bytes, reserved_tail: int = 0) -> int:
    """Bytes before the $FF fill tail — what the author actually spent.

    `reserved_tail` is a fixed always-occupied region at the end of the image
    (the Ultimax reset vectors at $FFFA). Those bytes are never $FF, so the
    fill heuristic has to stop short of them and count them separately —
    otherwise every Ultimax cart reports as completely full.
    """
    body = image[:len(image) - reserved_tail] if reserved_tail else image
    return len(body.rstrip(b"\xFF")) + reserved_tail
