"""Build Commodore 64 cartridge images from ca65 sources and .prg files.

Three author models share one pipeline: assemble into a ROM-address linker
config, pad the result to the exact size cartconv demands, convert. The boot
stub is generated unless the author supplies their own STARTUP segment.

Everything about *how a cartridge boots* is measured, not assumed:
8K/16K carts boot through the CBM80 signature the KERNAL reset scans for at
$8004; Ultimax and EasyFlash carts have no KERNAL to scan, so they boot
through the CPU reset vector at $FFFC.
"""

from __future__ import annotations

import re
import tempfile
from pathlib import Path

from .basic import tokenize
from .build import BuildError, _find_tool, _parse_deps, _run, build_asm
from .cartridge import (
    BANK_WINDOW,
    CRT_NAME_LEN,
    CartError,
    bin_to_crt,
    get_cart_type,
)
from .machines import get_profile

# Cart geometry, all $2000-aligned windows.
ROML_START = 0x8000
ROMH_START = 0xA000
ULTIMAX_START = 0xE000
VECTORS_ADDR = 0xFFFA
VECTORS_SIZE = 6

_ZP = "    ZP:   start = $0000, size = $0100;"
_SEG_COMMON = """\
    ZEROPAGE: load = ZP,   type = zp, optional = yes;
    STARTUP:  load = {rom}, type = ro, optional = yes;
    CODE:     load = {rom}, type = ro;
    RODATA:   load = {rom}, type = ro, optional = yes;
    DATA:     load = {rom}, type = ro, optional = yes;"""


def cart_linker_config(cart_type: str) -> str:
    """ld65 config placing code in ROM windows instead of at the BASIC start.

    DATA is `type = ro`: a cartridge's data segment lives in ROM and cannot be
    written. Mutable state belongs in a BSS segment the author places in RAM.
    """
    get_cart_type(cart_type)        # raises CartError naming the known types
    if cart_type == "8k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "}\n"
        )
    if cart_type == "16k":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROML: file = %O, start = ${ROML_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            f"    ROMH: file = %O, start = ${ROMH_START:04X}, "
            f"size = ${BANK_WINDOW:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROML')}\n"
            "    ROMH:     load = ROMH, type = ro, optional = yes;\n"
            "}\n"
        )
    if cart_type == "ultimax":
        return (
            "MEMORY {\n"
            f"{_ZP}\n"
            f"    ROM:  file = %O, start = ${ULTIMAX_START:04X}, "
            f"size = ${BANK_WINDOW - VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            f"    VEC:  file = %O, start = ${VECTORS_ADDR:04X}, "
            f"size = ${VECTORS_SIZE:04X}, fill = yes, fillval = $FF;\n"
            "}\n"
            "SEGMENTS {\n"
            f"{_SEG_COMMON.format(rom='ROM ')}\n"
            "    VECTORS:  load = VEC,  type = ro;\n"
            "}\n"
        )
    raise CartError(
        f"{cart_type!r} has no single-region linker config; use `cart build` "
        "with an EasyFlash manifest instead")


# The reset stub an 8K/16K cartridge boots through. $8000-$8001 is the cold
# vector, $8002-$8003 the warm/NMI vector, $8004-$8008 the signature the
# KERNAL reset routine scans for. Without the signature the machine silently
# boots to BASIC (measured).
_CBM80_STUB = """\
; Generated by c64-tools — 8K/16K cartridge boot stub.
.import cart_main
.segment "STARTUP"
        .word   _cart_cold              ; $8000 cold vector
        .word   _cart_cold              ; $8002 warm/NMI vector
        .byte   $C3,$C2,$CD,$38,$30     ; "CBM80" — the KERNAL scans for this
_cart_cold:
        sei
        cld
        ldx     #$FF
        txs
        jsr     $FDA3                   ; IOINIT  — CIAs, VIC, IRQ timer
        jsr     $FD50                   ; RAMTAS  — clears $0002-$0101, $0200-$03FF
        jsr     $FD15                   ; RESTOR  — KERNAL vectors to $0314
        jsr     $FF5B                   ; CINT    — VIC + screen editor
        cli
        jmp     cart_main
"""

# An Ultimax cartridge replaces the KERNAL, so there is nothing to call and no
# CBM80 scan: the CPU takes RESET straight from $FFFC.
_ULTIMAX_STUB = """\
; Generated by c64-tools — Ultimax cartridge boot stub.
; There is no KERNAL under an Ultimax cart: cart_main owns all hardware init,
; and only $0000-$0FFF is RAM.
.import cart_main
.segment "STARTUP"
_cart_reset:
        sei
        cld
        ldx     #$FF
        txs
        jmp     cart_main
.segment "VECTORS"
        .word   _cart_reset             ; $FFFA NMI
        .word   _cart_reset             ; $FFFC RESET
        .word   _cart_reset             ; $FFFE IRQ/BRK
"""


def boot_stub_source(cart_type: str) -> str:
    if cart_type in ("8k", "16k"):
        return _CBM80_STUB
    if cart_type == "ultimax":
        return _ULTIMAX_STUB
    raise CartError(f"no boot stub for cartridge type {cart_type!r}")


_STARTUP_RE = re.compile(r'^\s*\.segment\s+"STARTUP"', re.MULTILINE)


def has_own_startup(sources) -> bool:
    """True when the author supplies their own STARTUP segment — the opt-out.

    Scanned over the source and everything ca65 reports it included, so an
    author can keep their boot code in a shared .inc.
    """
    for src in sources:
        try:
            text = Path(src).read_text()
        except (OSError, UnicodeDecodeError):
            continue
        # Strip line comments so a mention in prose does not count.
        text = re.sub(r";.*$", "", text, flags=re.MULTILINE)
        if _STARTUP_RE.search(text):
            return True
    return False


def cart_title(raw: str) -> str:
    """Normalize a cartridge name for the 32-byte .crt name field."""
    t = str(raw).upper().strip()
    if not t:
        raise CartError("cartridge title is empty")
    if len(t) > CRT_NAME_LEN:
        raise CartError(
            f"title {t!r} is {len(t)} chars; the .crt name field holds "
            f"{CRT_NAME_LEN}")
    if not all(0x20 <= ord(c) <= 0x7E for c in t):
        raise CartError(f"title {t!r} has characters outside printable ASCII")
    return t


def _assemble(ca65: str, source: Path, obj: Path, dep: Path) -> tuple[Path, ...]:
    _run([ca65, "-g", str(source), "-o", str(obj), "--create-dep", str(dep)])
    return _parse_deps(dep, fallback=Path(source))


def _run_hint(crt: Path) -> str:
    return f"x64sc -ntsc -cartcrt {crt}"


def build_cart(source, out=None, cart_type: str = "8k",
               title: str | None = None) -> dict:
    """Assemble a cart-native .s into a bootable .crt.

    A boot stub is injected unless the source (or something it includes)
    defines its own STARTUP segment, in which case the author owns the boot
    sequence and must place the CBM80 header / reset vectors themselves.

    The padded raw ROM image is kept beside the .crt (same stem, `.bin`), the
    way build_asm keeps its label file: it is what a flasher or an emulator's
    raw-ROM mode wants, and regenerating it means re-running the whole build.
    """
    ct = get_cart_type(cart_type)
    if ct.max_banks > 1:
        raise CartError(
            f"{cart_type} is bank-switched; build it from a manifest with "
            "`c64 cart build game.ef.yaml`")
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")
    source = Path(source)
    crt = Path(out) if out is not None else source.with_suffix(".crt")
    labels = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    name = cart_title(title if title is not None else source.stem)
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        obj, dep = td / f"{source.stem}.o", td / "deps.d"
        deps = _assemble(ca65, source, obj, dep)
        objs = [str(obj)]
        if not has_own_startup(deps):
            stub_src = td / "_cartboot.s"
            stub_src.write_text(boot_stub_source(cart_type))
            stub_obj = td / "_cartboot.o"
            _run([ca65, str(stub_src), "-o", str(stub_obj)])
            objs.append(str(stub_obj))
        cfg = td / "cart.cfg"
        cfg.write_text(cart_linker_config(cart_type))
        try:
            _run([ld65, "-o", str(raw), "-C", str(cfg), "-Ln", str(labels), *objs])
        except BuildError as e:
            if "cart_main" in str(e):
                raise CartError(
                    f"{source}: the generated boot stub jumps to `cart_main`, "
                    "but the source does not export it. Add "
                    "`.export cart_main` (or supply your own STARTUP segment "
                    "to take over the boot sequence).\n" + str(e)
                ) from None
            raise
        # Ultimax parks its reset vectors in the last 6 bytes of the image.
        reserved = VECTORS_SIZE if ct.name == "ultimax" else 0
        used = _used_bytes(raw.read_bytes(), reserved)
        bin_to_crt(raw, crt, cart_type, name)
    return {"crt": str(crt), "bin": str(raw), "labels": str(labels),
            "title": name, "cart_type": cart_type, "run": _run_hint(crt),
            "bytes": used, "free": ct.image_bytes - used}


def _used_bytes(image: bytes, reserved_tail: int = 0) -> int:
    """Bytes before the $FF fill tail — what the author actually spent.

    `reserved_tail` is a fixed always-occupied region at the end of the image
    (the Ultimax reset vectors at $FFFA). Those bytes are never $FF, so the
    fill heuristic has to stop short of them and count them separately —
    otherwise every Ultimax cart reports as completely full.
    """
    body = image[:len(image) - reserved_tail] if reserved_tail else image
    return len(body.rstrip(b"\xFF")) + reserved_tail


# A wrapped program is copied out of ROM to its load address, then started.
# The BASIC path is the measured `RUN` equivalent: init the BASIC vectors and
# zero page, point VARTAB/ARYTAB/STREND past the program, CLR, then hand
# control to the interpreter loop.
_LAUNCHER = """\
; Generated by c64-tools — launcher cartridge wrapping a .prg.
.segment "STARTUP"
        .word   _cart_cold
        .word   _cart_cold
        .byte   $C3,$C2,$CD,$38,$30     ; "CBM80"
_cart_cold:
        sei
        cld
        ldx     #$FF
        txs
        jsr     $FDA3                   ; IOINIT
        jsr     $FD50                   ; RAMTAS
        jsr     $FD15                   ; RESTOR
        jsr     $FF5B                   ; CINT
        cli
{basic_init}\
        lda     #<_blob                 ; copy the embedded image down
        sta     $FB
        lda     #>_blob
        sta     $FC
        lda     #<${load_addr:04X}
        sta     $FD
        lda     #>${load_addr:04X}
        sta     $FE
        ldx     #_PAGES
        ldy     #$00
_page:  lda     ($FB),y
        sta     ($FD),y
        iny
        bne     _page
        inc     $FC
        inc     $FE
        dex
        bne     _page
{start}\
_blob:  .incbin "{prg_name}", 2         ; skip the 2-byte load address
_blob_end:
_PAGES  = (_blob_end - _blob + 255) / 256
"""

_BASIC_INIT = """\
        jsr     $E453                   ; BASIC vectors -> $0300
        jsr     $E3BF                   ; BASIC zero-page pointers
"""

_BASIC_START = """\
        lda     #<${prog_end:04X}       ; VARTAB / ARYTAB / STREND
        sta     $2D
        sta     $2F
        sta     $31
        lda     #>${prog_end:04X}
        sta     $2E
        sta     $30
        sta     $32
        jsr     $A659                   ; CLR
        jmp     $A7AE                   ; BASIC interpreter loop = RUN
"""

_ML_START = """\
        jmp     ${load_addr:04X}
"""


def launcher_source(load_addr: int, prog_end: int, kind: str,
                    prg_name: str = "wrapped.prg") -> str:
    if kind == "basic":
        basic_init, start = _BASIC_INIT, _BASIC_START.format(prog_end=prog_end)
    elif kind == "ml":
        basic_init, start = "", _ML_START.format(load_addr=load_addr)
    else:
        raise CartError(f"unknown wrap kind {kind!r} (use 'basic' or 'ml')")
    return _LAUNCHER.format(basic_init=basic_init, start=start,
                            load_addr=load_addr, prg_name=prg_name)


def wrap_prg(source, out=None, cart_type: str = "8k", title: str | None = None,
             model: str = "c64") -> dict:
    """Wrap an existing program in a launcher cartridge.

    `.bas` is tokenized first and `.s` assembled first, so any program this
    toolchain can build becomes a boot cartridge. The wrapped image is stored
    in ROM after the launcher and copied to its load address at boot.
    """
    if cart_type == "ultimax":
        raise CartError(
            "wrap-a-prg chains through the KERNAL and BASIC, and an Ultimax "
            "cartridge replaces them; use --cart-type 8k or 16k")
    ct = get_cart_type(cart_type)
    if ct.max_banks > 1:
        raise CartError(f"cannot wrap a .prg into a {cart_type} cartridge")
    source = Path(source)
    crt = Path(out) if out is not None else source.with_suffix(".crt")
    labels = crt.with_suffix(".lbl")
    raw = crt.with_suffix(".bin")
    name = cart_title(title if title is not None else source.stem)
    profile = get_profile(model)
    ca65 = _find_tool("ca65", "C64_TOOLS_CA65")
    ld65 = _find_tool("ld65", "C64_TOOLS_LD65")

    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        ext = source.suffix.lower()
        if ext == ".prg":
            prg = source
            kind = "basic" if _looks_like_basic(source, profile.basic_start) else "ml"
        elif ext == ".bas":
            prg = tokenize(source, td / "wrapped.prg", profile.basic_version)
            kind = "basic"
        elif ext == ".s":
            prg = build_asm(source, out_prg=td / "wrapped.prg",
                            basic_start=profile.basic_start).prg
            kind = "ml"
        else:
            raise CartError(
                f"cannot wrap {ext or source.name!r} (use .prg, .bas, or .s)")

        image = Path(prg).read_bytes()
        if len(image) < 3:
            raise CartError(
                f"{prg}: {len(image)} bytes — too short to hold a 2-byte load "
                "address and a program")
        load_addr = int.from_bytes(image[:2], "little")
        body = image[2:]
        prog_end = load_addr + len(body)

        budget = ct.image_bytes
        if len(body) + 256 > budget:            # 256 ≈ the launcher's own size
            nxt = "16k" if cart_type == "8k" else None
            hint = (f"; retry with --cart-type {nxt}" if nxt
                    else "; use the native or EasyFlash path")
            raise CartError(
                f"{source}: the program is {len(body)} bytes and will not fit "
                f"a {cart_type} cartridge ({budget} bytes){hint}")

        blob = td / "wrapped.prg"
        if Path(prg).resolve() != blob.resolve():
            blob.write_bytes(image)
        src_path = td / "_launcher.s"
        src_path.write_text(launcher_source(load_addr, prog_end, kind, blob.name))
        obj = td / "_launcher.o"
        _run([ca65, str(src_path), "-o", str(obj), "-I", str(td),
              "--bin-include-dir", str(td)])
        cfg = td / "cart.cfg"
        cfg.write_text(cart_linker_config(cart_type))
        try:
            _run([ld65, "-o", str(raw), "-C", str(cfg), "-Ln", str(labels),
                  str(obj)])
        except BuildError as e:
            if "range" in str(e).lower() or "overflow" in str(e).lower():
                nxt = "16k" if cart_type == "8k" else None
                hint = (f"; retry with --cart-type {nxt}" if nxt else
                        "; a program this large needs the native or EasyFlash path")
                raise CartError(
                    f"{source}: the wrapped program ({len(body)} bytes) plus the "
                    f"launcher does not fit a {cart_type} cartridge"
                    f"{hint}\n{e}") from None
            raise
        used = _used_bytes(raw.read_bytes())
        bin_to_crt(raw, crt, cart_type, name)

    return {"crt": str(crt), "bin": str(raw), "labels": str(labels),
            "title": name, "cart_type": cart_type, "run": _run_hint(crt),
            "bytes": used, "free": ct.image_bytes - used,
            "wrapped": str(source), "load_addr": load_addr, "kind": kind}


def _looks_like_basic(prg: Path, basic_start: int) -> bool:
    """A .prg loading at the BASIC start is treated as a BASIC program."""
    head = prg.read_bytes()[:2]
    return len(head) == 2 and int.from_bytes(head, "little") == basic_start
