#!/usr/bin/env python3
"""Convert the ASCII-art glyph sheet in charset.txt into ca65 .byte rows.

The C64 has no charset equivalent of `c64 sprite encode`, so this demo brings
its own converter (allowed by docs/graphics-and-sprites.md section 2). The
committed artifact is the generated chars.inc, not the art — the art is kept
because it is the only readable form of a multicolor glyph.

Input format (charset.txt):

    # comments and blank lines are ignored between blocks
    name: squid_a_left
    ...3
    ..33
    ...

Each block is a `name:` line followed by exactly 8 rows of exactly 4 legend
characters.  Legend (multicolor text mode, 2 bits per color-pixel):

    .  00  background          $D021
    1  01  shared color 1      $D022
    2  10  shared color 2      $D023
    3  11  the cell's own color (low 3 bits of its color-RAM nybble)

Usage:  python3 tools/charset.py tools/charset.txt > chars.inc
"""

from __future__ import annotations

import sys

LEGEND = {".": 0b00, "1": 0b01, "2": 0b10, "3": 0b11}
ROWS_PER_GLYPH = 8
PIXELS_PER_ROW = 4


class GlyphError(ValueError):
    """A block that does not describe exactly one 8x4 multicolor glyph."""


def parse(text: str) -> list[tuple[str, list[str]]]:
    """Split the sheet into (name, rows) blocks, validating each one."""
    glyphs: list[tuple[str, list[str]]] = []
    name: str | None = None
    rows: list[str] = []

    def close(lineno: int) -> None:
        if name is None:
            return
        if len(rows) != ROWS_PER_GLYPH:
            raise GlyphError(
                f"glyph {name!r} (ending at line {lineno}) has {len(rows)} rows, "
                f"expected {ROWS_PER_GLYPH}"
            )
        glyphs.append((name, list(rows)))

    for lineno, raw in enumerate(text.splitlines(), start=1):
        line = raw.rstrip("\n")
        stripped = line.strip()
        if stripped.startswith("#") or not stripped:
            continue
        if stripped.endswith(":") or stripped.startswith("name:"):
            close(lineno)
            name = stripped.removeprefix("name:").strip().rstrip(":")
            rows = []
            continue
        if name is None:
            raise GlyphError(f"line {lineno}: pixel row before any `name:` line")
        if len(line) != PIXELS_PER_ROW:
            raise GlyphError(
                f"glyph {name!r} line {lineno}: {len(line)} characters, "
                f"expected exactly {PIXELS_PER_ROW} ({line!r})"
            )
        bad = sorted(set(line) - set(LEGEND))
        if bad:
            raise GlyphError(
                f"glyph {name!r} line {lineno}: illegal legend characters {bad} "
                f"(legend is {''.join(LEGEND)})"
            )
        rows.append(line)
    close(len(text.splitlines()))
    if not glyphs:
        raise GlyphError("no glyphs found")
    return glyphs


def encode(row: str) -> int:
    """Pack 4 legend characters into one charset byte (2 bits per pixel)."""
    value = 0
    for char in row:
        value = (value << 2) | LEGEND[char]
    return value


def render(glyphs: list[tuple[str, list[str]]], first_code: int) -> str:
    out = [
        "; chars.inc — GENERATED by tools/charset.py from tools/charset.txt.",
        "; Do not edit by hand; edit the art and regenerate.",
        f"; {len(glyphs)} glyphs, 8 bytes each, patched over screen codes "
        f"{first_code}-{first_code + len(glyphs) - 1}.",
        "",
        "glyphs:",
    ]
    for offset, (name, rows) in enumerate(glyphs):
        out.append(f"        ; code {first_code + offset}: {name}")
        for row in rows:
            out.append(f"        .byte   %{encode(row):08b}    ; {row}")
    out.append("glyphs_end:")
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    path = argv[1] if len(argv) > 1 else "tools/charset.txt"
    first_code = int(argv[2]) if len(argv) > 2 else 64
    with open(path, encoding="utf-8") as handle:
        glyphs = parse(handle.read())
    sys.stdout.write(render(glyphs, first_code))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
