#!/usr/bin/env python3
"""Generate demos/1812/tables.inc — the demo's derived lookup tables.

Everything here is arithmetic the 6502 must not do at runtime: a 256-step
sine, the bitmap row-address table that replaces a multiply, the cell
x-offset table, the screen/colour attribute row tables, and the SID note
frequencies for the NTSC clock.

    python3 tools/gentables.py            # write tables.inc
    python3 tools/gentables.py --check    # verify the committed file matches

Stdlib only, runnable from anywhere.
"""

from __future__ import annotations

import math
import pathlib
import sys

# --- constants -------------------------------------------------------------

BITMAP = 0x2000          # SPEC.md 2.2
SCREEN = 0x0400
COLRAM = 0xD800
ROWS = 200               # bitmap pixel rows
CELLS = 40               # cells across
CELLROWS = 25

# The true NTSC clock is 1022727 Hz; `references/hardware.md` said 1022730 and
# has since been corrected. This keeps the older value ON PURPOSE: the note
# table committed beside this script was generated with it, and re-running
# with 1022727 would move three of the 72 entries (C#3, F6, A#6) by one LSB —
# 0.76 cents at worst, and only at C#3. Not worth a regenerated artifact, but
# it is a real diff, so change this only together with the table it produces.
NTSC_CLOCK = 1022730
SID_ACC = 16777216       # 2**24, the oscillator accumulator
C1_HZ = 32.70319566      # note index 1
NOTES = 72               # C1..B6


def _s8(v: int) -> int:
    """Two's-complement byte for a signed value."""
    return v & 0xFF


# --- the tables ------------------------------------------------------------

def sintab() -> list[int]:
    """sin over a 256-step circle, Q7 (127 = 1.0)."""
    return [_s8(round(127 * math.sin(2 * math.pi * i / 256))) for i in range(256)]


def rowaddr() -> list[int]:
    """Bitmap address of cell column 0 on pixel row y.

    Multicolour bitmap memory is 8-byte cells, not linear scanlines:
    base + (y & 248) * 40 + (y & 7).
    """
    return [BITMAP + (y & 248) * 40 + (y & 7) for y in range(ROWS)]


def xoff8() -> list[int]:
    """Byte offset of cell column c within a cell row: 8 * c, 0..312."""
    return [8 * c for c in range(CELLS)]


def attrscr() -> list[int]:
    return [SCREEN + 40 * r for r in range(CELLROWS)]


def attrcol() -> list[int]:
    return [COLRAM + 40 * r for r in range(CELLROWS)]


def notefreq() -> list[int]:
    """SID frequency values, note 1 = C1 .. note 72 = B6, NTSC clock.

    Fn = round(f * 2**24 / clock); f = C1 * 2**((n-1)/12).
    """
    out = []
    for n in range(1, NOTES + 1):
        f = C1_HZ * (2.0 ** ((n - 1) / 12.0))
        out.append(min(0xFFFF, round(f * SID_ACC / NTSC_CLOCK)))
    return out


# --- emission --------------------------------------------------------------

def _rows(values: list[int], per_line: int, fmt) -> list[str]:
    lines = []
    for i in range(0, len(values), per_line):
        chunk = values[i:i + per_line]
        lines.append("        .byte   " + ", ".join(fmt(v) for v in chunk))
    return lines


def _bytes_table(label: str, comment: list[str], values: list[int]) -> list[str]:
    out = [f"; {c}" for c in comment]
    out.append(f"{label}:")
    out += _rows(values, 8, lambda v: f"${v:02x}")
    out.append("")
    return out


def _word_table(label: str, comment: list[str], values: list[int]) -> list[str]:
    """A 16-bit table as split low/high byte arrays — the form 6502 indexing
    wants (lda tablel,x / lda tableh,x), not interleaved .word rows."""
    out = [f"; {c}" for c in comment]
    out.append(f"{label}l:")
    out += _rows([v & 0xFF for v in values], 8, lambda v: f"${v:02x}")
    out.append(f"{label}h:")
    out += _rows([v >> 8 for v in values], 8, lambda v: f"${v:02x}")
    out.append("")
    return out


def render() -> str:
    L: list[str] = []
    L.append("; tables.inc — GENERATED by tools/gentables.py.  Do not edit by hand;")
    L.append("; edit the generator and re-run it.  `gentables.py --check` fails if")
    L.append("; this file and the generator have drifted apart.")
    L.append("")
    L.append("        .segment \"RODATA\"")
    L.append("")

    L += _bytes_table(
        "sintab",
        ["sin over a 256-step angle, Q7: round(127 * sin(2*pi*i/256)),",
         "signed bytes.  cos(a) = sintab + ((a + 64) & 255)."],
        sintab(),
    )
    L += _word_table(
        "rowaddr",
        [f"Bitmap address of cell column 0 on pixel row y (0..{ROWS - 1}):",
         f"${BITMAP:04x} + (y & 248) * 40 + (y & 7).  Replaces a multiply in",
         "the innermost fill loop."],
        rowaddr(),
    )
    L += _word_table(
        "xoff8",
        [f"Byte offset of cell column c (0..{CELLS - 1}) within a cell row: 8 * c."],
        xoff8(),
    )
    L += _word_table(
        "attrscr",
        [f"Screen-RAM address of cell row r (0..{CELLROWS - 1}): ${SCREEN:04x} + 40 * r.",
         "Holds bit-pair 01 in the high nybble, 10 in the low nybble."],
        attrscr(),
    )
    L += _word_table(
        "attrcol",
        [f"Colour-RAM address of cell row r: ${COLRAM:04x} + 40 * r.",
         "Low nybble holds bit-pair 11."],
        attrcol(),
    )
    L += _word_table(
        "notefreq",
        ["SID frequency values for the NTSC clock: note 1 = C1 .. note 72 = B6,",
         f"Fn = round(f * {SID_ACC} / {NTSC_CLOCK}).  Note 0 is a rest and has",
         "no entry, so index with (note - 1)."],
        notefreq(),
    )
    return "\n".join(L) + "\n"


# --- main ------------------------------------------------------------------

def selftest() -> None:
    """Invariants worth failing loudly on."""
    s = sintab()
    assert s[0] == 0 and s[64] == 127 and s[128] == 0 and s[192] == _s8(-127), s[:1]
    r = rowaddr()
    assert r[0] == 0x2000 and r[1] == 0x2001 and r[8] == 0x2140, [hex(x) for x in r[:9]]
    assert r[199] == 0x3E07, hex(r[199])
    assert r[199] + 8 * 39 == 0x3F3F, "last bitmap byte"
    n = notefreq()
    assert abs(n[45] - 7218) <= 1, n[45]          # note 46 = A4, index 45
    assert n[36] * 2 == n[48] or abs(n[36] * 2 - n[48]) <= 2, (n[36], n[48])


def main(argv: list[str]) -> int:
    selftest()
    out = pathlib.Path(__file__).resolve().parent.parent / "tables.inc"
    text = render()
    if "--check" in argv:
        if not out.exists():
            print(f"{out} missing", file=sys.stderr)
            return 1
        if out.read_text() != text:
            print(f"{out} differs from the generator output", file=sys.stderr)
            return 1
        print("tables.inc matches")
        return 0
    out.write_text(text)
    nf = notefreq()
    print(f"wrote {out} ({len(text.splitlines())} lines)")
    print(f"  sintab[64]={sintab()[64]}  rowaddr[199]=${rowaddr()[199]:04x}"
          f"  notefreq[A4]={nf[45]}  notefreq[C1]={nf[0]}  notefreq[B6]={nf[71]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
