; chars.s -- the character set installer.
;
; The set is built in RAM at $3800 rather than copied from the character ROM
; and patched: every glyph this game puts on screen is its own, and an
; unpatched glyph of all zeros draws blank, which is exactly what an unused
; code should do.  The blocks come out of chars.inc, which tools/genart.sh
; regenerates from the ASCII art in tools/.
;
; Screen-code layout:
;
;   1-31    A-Z, then A-acute E-acute I-acute O-acute U-acute
;   33-60   `!`, ten blanks, `,` `-` `.` `/` 0-9 `:` N-tilde and inverted `!`
;   64-87   the settled-enemy 2x2 blocks: drone, sentinel, flagship, two
;           animation frames each, four quadrants each (TL TR BL BR)
;   88-99   three starfield layers, missile and bullet half-cell phases,
;           the bezel rail and grille, the life icon, a panel bracket
;
; The letters keep their ROM screen codes on purpose: `c64 screen` decodes
; every code through its *ROM* meaning, so HUD text still reads back as text
; and `wait --text` still matches, while the glyphs on screen are ours.
; Codes 64-99 decode to ROM graphics characters, so every assertion about
; the playfield is on `--codes` or `mem read`, never on decoded text.

        .segment "ENGINE"

installart:
        ; ---- blank the whole 2 KB set ------------------------------------
        lda     #<CHARSET
        sta     DST
        lda     #>CHARSET
        sta     DST+1
        ldy     #0
        tya
ia1:    sta     (DST),y
        iny
        bne     ia1
        inc     DST+1
        ldx     DST+1
        cpx     #>(CHARSET + $0800)
        bne     ia1

        ; ---- the three glyph blocks --------------------------------------
        lda     #<fontgly
        ldx     #>fontgly
        ldy     #1                      ; first screen code
        jsr     setglyphsrc
        lda     #<(fontgly_end - fontgly)
        ldx     #>(fontgly_end - fontgly)
        jsr     copyblock

        lda     #<punctgly
        ldx     #>punctgly
        ldy     #33
        jsr     setglyphsrc
        lda     #<(punctgly_end - punctgly)
        ldx     #>(punctgly_end - punctgly)
        jsr     copyblock

        lda     #<gamegly
        ldx     #>gamegly
        ldy     #64
        jsr     setglyphsrc
        lda     #<(gamegly_end - gamegly)
        ldx     #>(gamegly_end - gamegly)
        jsr     copyblock

        jmp     installsprites

; setglyphsrc -- A/X = source, Y = first screen code.  DST = CHARSET + Y*8.
setglyphsrc:
        sta     SRC
        stx     SRC+1
        tya
        ldx     #0
        stx     DST+1
        asl     a                       ; code*8, 16-bit
        rol     DST+1
        asl     a
        rol     DST+1
        asl     a
        rol     DST+1
        sta     DST
        lda     DST+1
        clc
        adc     #>CHARSET
        sta     DST+1
        rts

; copyblock -- copy A/X bytes from SRC to DST.
copyblock:
        sta     tmp0
        stx     tmp1
        ldy     #0
cb1:    lda     tmp1
        bne     cb2
        lda     tmp0
        beq     cb9
cb2:    lda     (SRC),y
        sta     (DST),y
        lda     tmp0
        bne     :+
        dec     tmp1
:       dec     tmp0
        iny
        bne     cb1
        inc     SRC+1
        inc     DST+1
        jmp     cb1
cb9:    rts

; The glyph data itself, regenerated by tools/genart.sh.
        .include "chars.inc"
