#!/bin/sh
# Regenerate demos/la-galaxia/chars.inc and sprites.inc from the ASCII art in
# this directory.  Run from the repository root:
#
#     sh demos/la-galaxia/tools/genart.sh
#
# Two converters sit in front of the standard encoders, each for an input
# format they do not read: genblocks.py splits the 16x16 enemy pictures into
# 8x8 quadrants, and gensprites.py turns the named, background-visible sprite
# sheet into the exact-width spaces-are-background sheets `c64 sprite encode`
# wants.  Both emit the encoders' own formats -- the encoding is still done by
# `c64 charset encode` and `c64 sprite encode`.
#
# `c64 charset encode` emits one contiguous block under a fixed `glyphs:`
# label, so each sheet is renamed on the way out and the three blocks live in
# one file.  chars.s installs them from a table of (source, first code, count).
set -e
C=".venv/bin/c64"
D="demos/la-galaxia"
T="$D/tools"

python3 "$T/genblocks.py" "$T/enemies.txt" -o "$T/blocks.txt"
cat "$T/blocks.txt" "$T/glyphs.txt" > "$T/game.txt"
python3 "$T/gensprites.py" "$T/sprites.txt" -o "$T"

{
  echo "; chars.inc -- GENERATED by tools/genart.sh from the ASCII art in"
  echo "; tools/.  Do not edit: edit charset.txt / punct.txt / enemies.txt /"
  echo "; glyphs.txt and re-run the script."
  echo ""
  $C charset encode "$T/charset.txt" --hires --first-code 1 \
      | sed 's/^glyphs/fontgly/'
  echo ""
  $C charset encode "$T/punct.txt" --hires --first-code 33 \
      | sed 's/^glyphs/punctgly/'
  echo ""
  $C charset encode "$T/game.txt" --hires --first-code 64 \
      | sed 's/^glyphs/gamegly/'
} > "$D/chars.inc"

{
  echo "; sprites.inc -- GENERATED by tools/genart.sh from tools/sprites.txt."
  echo "; Do not edit: edit the art and re-run the script."
  echo ""
  $C sprite encode "$T/sprites-hires.gen.txt" --hires | sed 's/^sprite/hspr/'
  echo ""
  $C sprite encode "$T/sprites-multicolor.gen.txt" | sed 's/^sprite/mspr/'
} > "$D/sprites.inc"

echo "chars.inc:   $(grep -c '\.byte' "$D/chars.inc") rows"
echo "sprites.inc: $(grep -c '\.byte' "$D/sprites.inc") rows"
