#!/bin/sh
# Regenerate demos/la-galaxia/chars.inc and sprites.inc from the ASCII art in
# this directory.  Run from the repository root:
#
#     sh demos/la-galaxia/tools/genart.sh
#
# One converter still sits in front of a standard encoder, for an input format
# it does not read: genblocks.py splits the 16x16 enemy pictures into the 8x8
# quadrants a charset is made of.  It emits `c64 charset encode`'s own format
# -- the encoding is still the encoder's.
#
# Everything else the encoders now read as authored.  `c64 sprite encode`
# takes the named, commented, visible-background sheet straight
# (`--background .`), and `--label` names each charset block, so nothing is
# `sed`-renamed on the way out.  chars.s installs the three glyph blocks from
# a table of (source, first code, count).
set -e
C=".venv/bin/c64"
D="demos/la-galaxia"
T="$D/tools"

python3 "$T/genblocks.py" "$T/enemies.txt" -o "$T/blocks.txt"
cat "$T/blocks.txt" "$T/glyphs.txt" > "$T/game.txt"

{
  echo "; chars.inc -- GENERATED by tools/genart.sh from the ASCII art in"
  echo "; tools/.  Do not edit: edit charset.txt / punct.txt / enemies.txt /"
  echo "; glyphs.txt and re-run the script."
  echo ""
  $C charset encode "$T/charset.txt" --hires --first-code 1 --label fontgly
  echo ""
  $C charset encode "$T/punct.txt" --hires --first-code 33 --label punctgly
  echo ""
  $C charset encode "$T/game.txt" --hires --first-code 64 --label gamegly
} > "$D/chars.inc"

# One sheet, both modes, one invocation.  The `hspr` prefix is the label
# sprites.s indexes off (`adc #<hspr0`): all 21 shapes are one contiguous
# 63-byte-per-shape run, hires first, in the order sprites.s's SPRBLK
# constants name them, so the base label is all the assembler needs.
{
  echo "; sprites.inc -- GENERATED by tools/genart.sh from tools/sprites.txt."
  echo "; Do not edit: edit the art and re-run the script."
  echo ""
  $C sprite encode "$T/sprites.txt" --background . | sed 's/^sprite/hspr/'
} > "$D/sprites.inc"

echo "chars.inc:   $(grep -c '\.byte' "$D/chars.inc") rows"
echo "sprites.inc: $(grep -c '\.byte' "$D/sprites.inc") rows"
