#!/usr/bin/env python3
"""Split the 16x16 enemy pictures in tools/enemies.txt into 8x8 quadrants.

`c64 charset encode` reads 8x8 ASCII-art glyphs; a settled enemy in this game
is a 2x2 character block, which is a 16x16 picture.  This is the one input
format the encoder does not cover, so the conversion lives here and the
encoding still goes through the standard tool: this script writes a sheet in
exactly the form `c64 charset encode --hires` expects.

    python3 tools/genblocks.py tools/enemies.txt -o tools/blocks.txt
    python3 tools/genblocks.py tools/enemies.txt --check

Quadrant order is TL, TR, BL, BR, which is screen-matrix order: the top-left
cell, then the cell to its right, then the two below.  formation.s writes the
four codes in that order and never has to remember a mapping.

The --check pass asserts what the renderer relies on and a typo would break:
every picture is exactly 16 rows of exactly 16 legend characters, no picture
is empty, and no two pictures are identical (which would mean an animation
frame that does not animate).
"""

from __future__ import annotations

import argparse
import sys

LEGEND = set(".#")
SIZE = 16
QUADS = ("tl", "tr", "bl", "br")


def parse(path: str) -> list[tuple[str, list[str]]]:
    """Read the sheet into (name, 16 rows) pairs, reporting slips by line."""
    pics: list[tuple[str, list[str]]] = []
    name: str | None = None
    rows: list[str] = []
    with open(path, encoding="utf-8") as fh:
        for lineno, raw in enumerate(fh, 1):
            line = raw.rstrip("\n")
            if not line.strip():
                continue
            if line.lstrip().startswith("#") and not (
                len(line) == SIZE and set(line) <= LEGEND
            ):
                continue
            if line.rstrip().endswith(":"):
                if name is not None:
                    pics.append((name, rows))
                name, rows = line.rstrip()[:-1].strip(), []
                continue
            if name is None:
                sys.exit(f"{path}:{lineno}: art before any `name:` header")
            if len(line) != SIZE or not set(line) <= LEGEND:
                sys.exit(
                    f"{path}:{lineno}: picture '{name}' row {len(rows) + 1} "
                    f"must be {SIZE} characters of '.#', got {len(line)}"
                )
            rows.append(line)
    if name is not None:
        pics.append((name, rows))
    return pics


def check(path: str, pics: list[tuple[str, list[str]]]) -> None:
    if not pics:
        sys.exit(f"{path}: no pictures")
    seen: dict[str, str] = {}
    for name, rows in pics:
        if len(rows) != SIZE:
            sys.exit(f"{path}: '{name}' must be {SIZE} rows, got {len(rows)}")
        if not any("#" in r for r in rows):
            sys.exit(f"{path}: '{name}' is blank")
        key = "\n".join(rows)
        if key in seen:
            sys.exit(f"{path}: '{name}' is identical to '{seen[key]}'")
        seen[key] = name


def quadrants(rows: list[str]) -> list[list[str]]:
    half = SIZE // 2
    return [
        [r[:half] for r in rows[:half]],
        [r[half:] for r in rows[:half]],
        [r[:half] for r in rows[half:]],
        [r[half:] for r in rows[half:]],
    ]


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("source", help="the 16x16 picture sheet")
    ap.add_argument("-o", "--out", help="write the 8x8 sheet here")
    ap.add_argument(
        "--check", action="store_true", help="validate only, write nothing"
    )
    args = ap.parse_args()

    pics = parse(args.source)
    check(args.source, pics)
    if args.check:
        print(f"{args.source}: {len(pics)} pictures, {len(pics) * 4} glyphs, ok")
        return

    out = [
        "# GENERATED by tools/genblocks.py from tools/enemies.txt -- do not edit.",
        f"# {len(pics)} pictures, {len(pics) * 4} glyphs, quadrant order TL TR BL BR.",
        "",
    ]
    for name, rows in pics:
        for tag, quad in zip(QUADS, quadrants(rows)):
            out.append(f"{name}_{tag}:")
            out.extend(quad)
            out.append("")
    text = "\n".join(out)
    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(text)
        print(f"wrote {args.out}: {len(pics) * 4} glyphs")
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
